### ISSUE TITLE
Footer Science checker : Pour améliorer le SEO 

### ISSUE THREAD

**Issue by roxanedepauw** [opscidia/science-checker#11]
Mettre les titres avec les URL dans le footer de la page du science checker 

VF : 

Colonne 1 : 
- Logo ( https://www.opscidia.com/fr/) 
- Autres outils scientifiques (https://www.opscidia.com/fr/solution-de-veille-technologique/) 
- Autres projets d'Opscidia (https://www.opscidia.com/fr/projet-de-veille-technologique-sur-mesure/) 

Colonne 2 : 
- Moteur de recherche scientifique : (https://www.opscidia.com/fr/moteur-de-recherche-scientifique/) 
- Détecteur de tendances technologie :  (https://www.opscidia.com/fr/trend-graphique-analyse-technologique/) 
- Rédaction de rapports scientifiques avec l'IA :(https://www.opscidia.com/fr/generation-des-raports-scientifique/) 
- Détecteur de relation en les concepts technologique : (https://www.opscidia.com/fr/mappings-de-concepts-technologiques/ ) 
------------------------------------------------------------------------------------------
VE : 

Colonne 1 : 
- Logo ( https://www.opscidia.com/) 
- Other scientific tools (https://www.opscidia.com/solution-de-veille-technologique/) 
- Other Opscidia's projects (https://www.opscidia.com/projet-de-veille-technologique-sur-mesure/) 

Colonne 2 : 
- Scientific search engine: (https://www.opscidia.com/moteur-de-recherche-scientifique/) 
- Technology trend finder: (https://www.opscidia.com/trend-graphique-analyse-technologique/) 
- Scientific report writing with AI:(https://www.opscidia.com/fr/generation-des-raports-scientifique/) 
- Technology concept relationship detector: (https://www.opscidia.com/mappings-de-concepts-technologiques/)

**Comment by Lrakotoson** [comment]
J'ai mis par défaut les liens VE. Le module utilisé ne permet pas de switcher les liens

**Comment by letailli** [comment]
OK mais pour les liens en VE uniquement mais il y a une coquille sur "Scientific report writing with AI"
Tu as mis :
https://www.opscidia.com/fr/generation-des-raports-scientifique/
au lieu de :
https://www.opscidia.com/generation-des-raports-scientifique/

**Comment by letailli** [comment]
OK
